#!/bin/sh

#Quick and dirty script to email wlan0 and eth0 addresses to you at boot
#Be sure you have mailx (sudo apt-get install heirloom-mailx
#Edit cron with crontab -e and then at the bottom of the file add @reboot  /path/to/this-script
#Can also be triggered with init.d and rc.local
#May have to chmod +x after copy

ETH=$(ip addr list eth0 |grep inet |cut -d' ' -f6|cut -d/ -f1)
WLAN=$(ip addr list wlan0 |grep inet |cut -d' ' -f6|cut -d/ -f1)
HOSTNAME=$(hostname)
BOTH="Ethernet Address: $ETH \n Wireless Address: $WLAN"
#echo "Ethernet Address:" $ETH
#echo "Wireless Address:" $WLAN

echo "$BOTH" | mailx -v -s "$HOSTNAME is online." -S smtp-use-starttls -S ssl-verify=ignore -S smtp-auth=login -S smtp=smtp.gmail.com:587 -S from=pi@pi.com -S smtp-auth-user="YOUR-GMAIL-ADDRESS" -S smtp-auth-password="YOUR-GMAIL-PASSWORD" "DESTINATION-EMAIL"
#Be sure to include "@gmail.com" in the auth user section, also keep the quotes around your password.
