#!/bin/sh
HOSTNAME=$(hostname)
initialpub=$(curl icanhazip.com)
reported=$(curl icanhazip.com)
ETH=$(ip addr list eth0 |grep inet |cut -d' ' -f6|cut -d/ -f1)
WLAN=$(ip addr list wlan0 |grep inet |cut -d' ' -f6|cut -d/ -f1)

BOTH="Ethernet Address: $ETH \nWireless Address: $WLAN \nPublic Address: $initialpub"
echo $BOTH | mailx -s "$HOSTNAME is online" DESTINATION


#Check for change in IP after boot
while [ 1 > 0 ]
do
 reported=$(curl icanhazip.com)
 if [ $reported = $initialpub ]
 then
 sleep 300
 else
 BOTH2="Ethernet Address: $ETH \nWireless Address: $WLAN \nPublic Address: $reported \nDomain aneis.ch has been updated."
 echo $BOTH2 | mailx -s "$HOSTNAME Has New Public Address" DESTINATION
 unset initialpub
 initialpub=$reported
 curl "https://dynamicdns.park-your-domain.com/update?host=@&domain=aneis.ch&password=7f1a5e19575740bf98a855c42a775807&ip=`curl -s echoip.com`"
fi
done

